#! /usr/bin/ruby

class Car

  def name
    @name
  end
  def brand
    @brand
  end
  def name=(value)
    @name = value
  end
  def brand=(value)
    @brand = value
  end

  def to_s
  puts "Name: #{@name} Brand: #{@brand}"
  end 

end