#! /usr/bin/ruby

class Car

  def name
    @name
  end
  def brand
    @brand
  end
  def name=(value)
    @name = value
  end
  def brand=(value)
    @brand = value
  end

  def to_s
  puts "Name: #{@name} Brand: #{@brand}"
  end 

  def driver
    @driver
  end
  def driver=(new_driver)
    @driver = new_driver
  end
  
end


class People
  
  def name
    @name
  end
  def name=(value)
    @name = value
  end
  def age
    @age
  end
  def age=(value)
    @age = value
  end

end

car1 = Car.new()
car1.name = "Astra"
car1.brand = "Opel"

p1 = People.new()
p1.name = "Yann"
p1.age = 19
p2 = People.new()
p2.name = "Nicolas"
p2.age = 17
p3 = People.new()
p3.name = "Véronique"
p3.age = 48
p4 = People.new()
p4.name = "Roland"
p4.age = 51
p5 = People.new()
p5.name = "Coline"
p5.age = 14
p6 = People.new()
p6.name = "Intru"
p6.age = 200

car1.driver = p1



