#! /usr/bin/ruby

class Car

  def name
    @name
  end
  def brand
    @brand
  end
  def name=(value)
    @name = value
  end
  def brand=(value)
    @brand = value
  end

  def to_s
  puts "Name: #{@name} Brand: #{@brand}"
  end 

  def driver
    @driver
  end
  def driver=(new_driver)
    @driver = new_driver
  end
  
end


car1 = Car.new()
car1.name = "Astra"
car1.brand = "Opel"

class People
  
  def name
    @name
  end
  def name=(value)
    @name = value
  end
  def age
    @age
  end
  def age=(value)
    @age = value
  end

end